export const ADD_NOTIFICATION_SUCCESS = "DATA ADDED SUCCESSFULLY";
export const DELETE_NOTIFICATION_SUCCESS = "DATA DELETED SUCCESSFULLY";
export const UPDATE_NOTIFICATION_SUCCESS = "DATA UPDATED SUCCESSFULLY";
export const ADD_NOTIFICATION_FAILED = "DATA COULD NOT BE ADDED";
export const DELETE_NOTIFICATION_FAILED = "DATA COULD NOT BE DELETED";
export const UPDATE_NOTIFICATION_FAILED = "DATA COULD NOT BE UPDATED";

export const CHANGE_PASSWORD_SUCCESS = "PASSWORD CHANGE SUCCESSFULLY";
export const LOGIN_DETAILS_INVALID = "LOGIN DETAILS INVALID";